spring:
  rabbitmq:
    # 连接信息
    host: 192.168.1.9      # 替换为您的 Ubuntu 服务器 IP
    port: 5672             # 默认 AMQP 端口
    username: admin        # 您在 RabbitMQ 中创建的用户名
    password: 123456 # 对应的密码
    virtual-host: /
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        multiplier: 2.0
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          multiplier: 2.0

  datasource:
    username: root
    password: 19859351310
    url: jdbc:mysql://localhost:3306/ticket?useSSL=false&charsetEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50

  data:
    redis:
      host: 192.168.1.9
      port: 6379
      database: 2
      timeout: 5000
      lettuce:
        pool:
          max-active: 100   #
          max-idle: 50
          min-idle: 10
          max-wait: 5000ms  # 获取连接最大等待时间

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
mybatis-plus:
  executor-type: batch
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-executor-type: batch
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-4d9a8f600ad24543bb3630543f98f64e


      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-4d9a8f600ad24543bb3630543f98f64e
logging:
  config: classpath:logback-spring.xml  # 显式指定


minio:
  endpoint: http://192.168.1.9:9000
  access-key: admin
  secret-key: 12345678
  bucket-name: bucket-name

